<!-- TOP LANDING SECTION -->
<div style="width:100%; height:90px; background-color:#fafafa; border-bottom:solid 1px #dcdde0;">
	<!-- logo -->
	<div style="float: left;">
		<a href="<?php echo base_url();?>index.php?home">
		<img src="<?php echo base_url();?>/assets/global/logo.png" style="margin: 18px 40px; height: 50px;" />
		</a>
	</div>
</div>
<div style="width:100%; height:100%; background-color:#f5f5f5; border-bottom:solid 1px #dcdde0;">
<div class="container"  >
	<div class="row">
			<div class="col-lg-12">
			<h4 class="black_text">Terms of Use</h4>	
			<h4 class="black_text">Last updated March 28, 2024</h4>
			<p>Happy Watch 99 provides a personalized subscription service that allows our members to access movies and Live TV ("Happy Watch 99 content") streamed over the Internet to certain Internet-connected TV's, computers and other devices ("Happy Watch 99 ready devices"). 
You have accepted these Terms of Use, which govern your use of our service. Personally identifying information is subject to our Privacy Statement, the terms of which are incorporated herein. Please review our Privacy Statement to understand our practices. 
As used in these Terms of Use, "Happy Watch 99 service", "our service" or "the service" means the personalized service provided by Happy Watch 99 for discovering and watching Happy Watch 99 content, including all features and functionalities, recommendations and reviews, the website, and user interfaces, as well as all content and software associated with our service. 
YOU AGREE TO THE ARBITRATION AGREEMENT AND CLASS ACTION WAIVER DESCRIBED IN SECTION 7 TO RESOLVE ANY DISPUTES WITH HAPPY WATCH 99 (EXCEPT FOR MATTERS THAT MAY BE TAKEN TO SMALL CLAIMS COURT). 
</p>

					<h5 class="black_text">1.	MEMBERSHIP</h5>
					<p>1.1. Your Happy Watch 99 membership will continue and automatically renew until terminated. To use the Happy Watch 99 service you must have Internet access and a Happy Watch 99 ready device and provide us with one or more Payment Methods. "Payment Method" means a current, valid, accepted method of payment, as may be updated from time to time and which may include payment through your account with a third party. You must cancel your membership before it renews in order to avoid billing of the membership fees for the next billing cycle to your Payment Method (see "Cancellation" below). </p>
					<p>1.2. We may offer a number of membership plans, including special promotional plans or memberships offered by third parties in conjunction with the provision of their own products and services. We are not responsible for the products and services provided by such third parties. Some membership plans may have differing conditions and limitations, which will be disclosed at your sign-up or in other communications made available to you. You can find specific details regarding your Happy Watch 99 membership by visiting our website and clicking on the "Account" link. </p>
					<h5 class="black_text">2.	FREE TRIALS </h5>
					<p>2.1. Your Happy Watch 99 membership may start with a free trial. The duration of the free trial period of your membership lasts will be specified during sign-up and is intended to allow new and certain former members to try the service. </p>
					<p>2.2. Free trial eligibility is determined by Happy Watch 99 at its sole discretion and we may limit eligibility or duration to prevent free trial abuse. We reserve the right to revoke the free trial and put your account on hold in the event that we determine that you are not eligible. Members of households with an existing or recent Happy Watch 99 membership are not eligible. We may use information such as device ID, method of payment or an account email address used with an existing or recent Happy Watch 99 membership to determine eligibility. For combinations with other offers, restrictions may apply. </p>
					<p>2.3. We will charge the membership fee for your next billing cycle to your Payment Method at the end of the free trial period and your membership will automatically renew unless you cancel your membership prior to the end of the free trial period. To view the applicable membership price and end date of your free trial period, visit our website and clicking on the "Account" link.</p>
					
					<h5 class="black_text">3.	BILLING AND CANCELLATION </h5>
					<p>3.1. Billing Cycle. The membership fee for the Happy Watch 99 service any other charges you may incur in connection with your use of the service, such as taxes and possible transaction fees, will be charged to your Payment Method on the specific billing date indicated on your "Account" page. The length of your billing cycle will depend on the type of subscription that you choose when you sign-up for the service. Membership fees are fully earned upon payment. In some cases your payment date may change, for example if your Payment Method has not successfully settled or if your paid membership began on a day not contained in a given month. Visit our website and click on the "Billing details" link on the "Account" page to see your next payment date. We may authorize your Payment Method in anticipation of membership or service-related charges through various methods, including authorizing it up to approximately one month of service as soon as you register. In some instances, your available balance or credit limit may be reduced to reflect the authorization during your free trial period. </p>
					<p>3.2. Payment Methods. To use the Happy Watch 99 service you must provide one or more Payment Methods. You authorize us to charge any Payment Method associated to your account in case your primary Payment Method is declined or no longer available to us for payment of your subscription fee. You remain responsible for any uncollected amounts. If a payment is not successfully settled, due to expiration, insufficient funds, or otherwise, and you do not cancel your account, we may suspend your access to the service until we have successfully charged a valid Payment Method. For some Payment Methods, the issuer may charge you certain fees, such as foreign transaction fees or other fees relating to the processing of your Payment Method. Check with your Payment Method service provider for details. </p>
					<p>3.3 Updating your Payment Methods. You can update your Payment Methods by going to the "Account" page. We may also update your Payment Methods using information provided by the payment service providers. Following any update, you authorize us to continue to charge the applicable Payment Method(s). </p>
					<p>3.4. Cancellation. You can cancel your Happy Watch 99 membership at any time, and you will continue to have access to the Happy Watch 99 service through the end of your billing period. To cancel, go to the "Account" page on our website and follow the instructions for cancellation. If you cancel your membership, your account will automatically close at the end of your current billing period. To see when your account will close, click "Billing details" on the "Account" page. If you signed up for Happy Watch 99 using your account with a third party as a Payment Method and wish to cancel your Happy Watch 99 membership, you may need to do so through that third party, for example by visiting your account with the applicable third party and turning off auto-renew, or unsubscribing from the Happy Watch 99 service through that third party. You may also find billing information about your Happy Watch 99 membership by visiting your account with the applicable third party. </p>
					<p>3.5. Changes to the Price and Subscription Plans. We reserve the right to change our subscription plans or adjust pricing for our service or any components thereof in any manner and at any time as we may determine in our sole and absolute discretion. Except as otherwise expressly provided for in these Terms of Use, any price changes or changes to your subscription plan will take effect following notice to you. </p>
					<p>3.6. No Refunds. Payments are nonrefundable and there are no refunds or credits for partially used periods. Following any cancellation, however, you will continue to have access to the service through the end of your current billing period. At any time, and for any reason, we may provide a refund, discount, or other consideration to some or all of our members ("credits"). The amount and form of such credits, and the decision to provide them, are at our sole and absolute discretion. The provision of credits in one instance does not entitle you to credits in the future for similar instances, nor does it obligate us to provide credits in the future, under any circumstance. </p>
					
					<h5 class="black_text">4.	HAPPY WATCH 99 SERVICE</h5>
<p>4.1. You must be 18 years of age, or the age of majority in your province, territory or country, to become a member of the Happy Watch 99 service. Individuals under the age of 18, or applicable age of majority, may utilize the service only with the involvement of a parent or legal guardian, under such person's account and otherwise subject to these Terms of Use. </p>
<p>4.2. The Happy Watch 99 service and any content viewed through our service are for your personal and non-commercial use only and may not be shared with individuals beyond your household. During your Happy Watch 99 membership, we grant you a limited, non-exclusive, non-transferable right to access the Happy Watch 99 service and view Happy Watch 99 content through the service. Except for the foregoing, no right, title or interest shall be transferred to you. You agree not to use the service for public performances. </p>

<p>4.3. You may view Happy Watch 99 content primarily within the country in which you have established your account and only in geographic locations where we offer our service and have licensed such content. The content that may be available to watch will vary by geographic location and will change from time to time. The number of devices on which you may simultaneously watch depends on your chosen subscription plan and is specified on the "Account" page. </p>
<p>4.4. The Happy Watch 99 service, including the content library, is regularly updated. In addition, we continually test various aspects of our service, including but not limited to our website, user interfaces, promotional features and availability of Happy Watch 99 content. You can turn off tests participation at any time by visiting the "Account" page and changing the "Test participation" settings. </p>
<p>4.5. Some Happy Watch 99 content is available for temporary download and offline viewing on certain supported devices ("Offline Titles"). Limitations apply, including restrictions on the number of Offline Titles per account, the maximum number of devices that can contain Offline Titles, the time period within which you will need to begin viewing Offline Titles and how long the Offline Titles will remain accessible. Some Offline Titles may not be playable in certain countries and if you go online in a country where you would not be able to stream that Offline Title, the Offline Title will not be playable while you are in that country. </p>
<p>4.6. You agree to use the Happy Watch 99 service, including all features and functionalities associated therewith, in accordance with all applicable laws, rules and regulations, or other restrictions on use of the service or content therein. Except as explicitly authorized in these Terms of Use, you agree not to archive, download, reproduce, distribute, modify, display, perform, publish, license, create derivative works from, offer for sale, or use content and information contained on or obtained from or through the Happy Watch 99 service. You also agree not to circumvent, remove, alter, deactivate, degrade or thwart any of the content protections in the Happy Watch 99 service; use any robot, spider, scraper or other automated means to access the Happy Watch 99 service; decompile, reverse engineer or disassemble any software or other products or processes accessible through the Happy Watch 99 service; insert any code or product or manipulate the content of the Happy Watch 99 service in any way; or use any data mining, data gathering or extraction method. In addition, you agree not to upload, post, e-mail or otherwise send or transmit any material designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment associated with the Happy Watch 99 service, including any software viruses or any other computer code, files or programs. We may terminate or restrict your use of our service if you violate these Terms of Use or are engaged in illegal or fraudulent use of the service. </p>
<p>4.7. The quality of the display of the Happy Watch 99 content may vary from device to device, and may be affected by a variety of factors, such as your location, the bandwidth available through and/or speed of your Internet connection. HD, Ultra HD and HDR availability is subject to your Internet service and device capabilities. Not all content is available in all formats, such as HD, Ultra HD or HDR and not all plans allow you to receive content in all formats. Default playback settings on cellular networks exclude HD, Ultra HD and HDR content. The minimum connection speed for SD quality is 0.5 Mbps; however, we recommend a faster connection for improved video quality. A download speed of at least 5.0 Mbps per stream is recommended to receive HD content (defined as a resolution of 720p or higher). A download speed of at least 25.0 Mbps per stream is recommended to receive Ultra HD (defined as a resolution of 1080p or higher) and HDR content. You are responsible for all Internet access charges. Please check with your Internet provider for information on possible Internet data usage charges. Happy Watch 99 makes no representations or warranties about the quality of your watching experience on your display. The time it takes to begin watching Happy Watch 99 content show will vary based on a number of factors, including your location, available bandwidth at the time, the Happy Watch 99 content you have selected and the configuration of your Happy Watch 99 ready device. </p>
<p>4.8. Happy Watch 99 software may solely be used for authorized streaming and viewing of content from Happy Watch 99 through Happy Watch 99 ready devices. This software may vary by device and medium, and functionalities may also differ between devices. By using our service, you agree to receive, without further notice or prompting, updated versions of the Happy Watch 99 and related third-party software. If you do not accept the foregoing terms, do not use our service. </p>
<p>4.9. By using our service, you agree to look solely to the entity that manufactured and/or sold you the Happy Watch 99 ready device for any issues related to the device and its compatibility with the Happy Watch 99 service. We do not take responsibility or otherwise warrant the performance of Happy Watch 99 ready devices, including the continued compatibility with our service. If your Happy Watch 99 ready device is sold, lost or stolen, please deactivate the Happy Watch 99 ready device. If you fail to log out or deactivate your device, subsequent users may access the Happy Watch 99 service through your account and may be able to access certain of your account information. To deactivate a device, follow instructions on the "Account" page of our website. </p>

<h5 class="black_text">5.	Passwords and Account Access.</h5>
<p>The member who created the Happy Watch 99 account and whose Payment Method is charged (the "Account Owner") has access and control over the Happy Watch 99 account and the Happy Watch 99 ready devices that are used to access our service and is responsible for any activity that occurs through the Happy Watch 99 account. To maintain control over the account and prevent anyone from accessing the account (which could include information on viewing history for the account), the Account Owner should maintain control over the Happy Watch 99 ready devices that are used to access the service and not reveal the password or details of the Payment Method associated to the account to anyone. You are responsible for updating and maintaining the accuracy of the information you provide to us relating to your account. We can terminate your account or place your account on hold in order to protect you, Happy Watch 99 or our partners from identity theft or other fraudulent activity. Happy Watch 99 is not obligated to credit or discount a membership for holds placed on the account by either a representative of Happy Watch 99 or by the automated processes of Happy Watch 99. 

</p>

<h5 class="black_text">6.	DISCLAIMERS OF WARRANTIES AND LIMITATIONS ON LIABILITY</h5>
<p>6.1. THE HAPPY WATCH 99 SERVICE AND ALL CONTENT AND SOFTWARE ASSOCIATED THEREWITH, OR ANY OTHER FEATURES OR FUNCTIONALITIES ASSOCIATED WITH THE HAPPY WATCH 99 SERVICE, ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. HAPPY WATCH 99 DOES NOT GUARANTEE, REPRESENT, OR WARRANT THAT YOUR USE OF THE HAPPY WATCH 99 SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. HAPPY WATCH 99 SPECIFICALLY DISCLAIMS LIABILITY FOR THE USE OF APPLICATIONS, HAPPY WATCH 99 READY DEVICES, AND HAPPY WATCH 99 SOFTWARE (INCLUDING THEIR CONTINUING COMPATIBILITY WITH OUR SERVICE). </p>
<p>6.2. TO THE EXTENT PERMISSIBLE UNDER APPLICABLE LAWS, IN NO EVENT SHALL HAPPY WATCH 99, OR ITS SUBSIDIARIES OR ANY OF THEIR SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES OR LICENSORS BE LIABLE (JOINTLY OR SEVERALLY) TO YOU FOR PERSONAL INJURY OR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER. </p>
<p>6.3. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES. THEREFORE, SOME OF THE ABOVE LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU. </p>
<p>6.4. NOTHING IN THESE TERMS OF USE SHALL AFFECT ANY NON-WAIVABLE STATUTORY RIGHTS THAT APPLY TO YOU. </p>

<h5 class="black_text">7.	MISCELLANEOUS</h5>
<p>7.1. Governing Law. These Terms of Use shall be governed by and construed in accordance with the laws of the state of Delaware, U.S.A. without regard to conflict of laws provisions. These terms will not limit any consumer protection rights that you may be entitled to under the mandatory laws of your state of residence. 

</p>
<p>7.2. Unsolicited Materials. Happy Watch 99 does not accept unsolicited materials or ideas for Happy Watch 99 content, and is not responsible for the similarity of any of its content or programming in any media to materials or ideas transmitted to Happy Watch 99. Should you send any unsolicited materials or ideas, you do so with the understanding that no additional consideration of any sort will be provided to you, and you are waiving any claim against Happy Watch 99 and its affiliates regarding the use of such materials and ideas, even if material or an idea is used that is substantially similar to the material or idea you sent. </p>
<p>7.3. Feedback. Happy Watch 99 is free to use any comments, information, ideas, concepts, reviews, or techniques or any other material contained in any communication you may send to us ("Feedback"), including responses to questionnaires or through postings to the Happy Watch 99 service, including the Happy Watch 99 website and user interfaces, worldwide and in perpetuity without further compensation, acknowledgement or payment to you for any purpose whatsoever including, but not limited to, developing, manufacturing and marketing products and creating, modifying or improving the Happy Watch 99 service. In addition, you agree not to enforce any "moral rights" in and to the Feedback, to the extent permitted by applicable law. </p>
<p>7.4. Customer Support. To find more information about our service and its features, or if you need assistance with your account, please email us at support@happywatch99. In certain instances, Customer Service may best be able to assist you by using a remote access support tool through which we have full access to your computer. If you do not want us to have this access, you should not consent to support through the remote access tool, and we will assist you through other means. In the event of any conflict between these Terms of Use and information provided by Customer Service or other portions of our website, these Terms of Use will control. </p>
<p>7.5. Survival. If any provision or provisions of these Terms of Use shall be held to be invalid, illegal, or unenforceable, the validity, legality and enforceability of the remaining provisions shall remain in full force and effect. </p>
<p>7.6. Changes to Terms of Use and Assignment. Happy Watch 99 may, from time to time, change these Terms of Use. Such revisions shall be effective immediately; provided however, for existing members, such revisions shall, unless otherwise stated, be effective 30 days after posting. We may assign our agreement with you to any affiliated company or to any entity that succeeds to all or substantially all of our business or assets related to the applicable Happy Watch 99 service. </p>
<p>7.7. Communication Preferences. We will send you information relating to your account (e.g. payment authorizations, invoices, changes in password or Payment Method, confirmation messages, notices) in electronic form only, for example via emails to your email address provided during registration. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing. </p>

		</div>
		<div class="col-lg-12" style="margin:20px;">
			<div class="row">
				<?php
					echo $this->db->get_where('settings',array('type'=>'privacy_policy'))->row()->description;
				?>
			</div>
		</div>
	</div>
	<?php include 'footer.php';?>
</div>
</div>